### ISSUE TITLE
"ListView.separated "在最新版本的flutter中已经废弃了，请问你开发使用的哪个版本的flutter，能否提供下，非常感谢

### ISSUE THREAD

**Issue by bngwong** [PopeyeLau/Flutter_YYeTs#1]
error: The method 'separated' isn't defined for the class 'ListView'. (undefined_method at [yyets] lib/pages/comment.dart:46)

**Comment by bngwong** [comment]
(Channel beta, v0.5.1, on Linux, locale zh_CN.UTF-8)
这是我目前使用的flutter版本

**Comment by popeyelau** [comment]
@bngwong 
`ListView.separated ` 是 dev 中新增的。请使用 dev channel. 

$`flutter channel dev`
